title: Tieumi's Blog
email: your.email@example.com
description: Personal blog on embedding geometry and LLMs.
baseurl: ""
url: "https://tieumi221e.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
